config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  get 'signup' => 'users#new'
  resources :tasks
  resources :users
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  post 'twilio/voice' => 'twilio#voice'
  post 'notifications/notify' => 'notifications#notify'
  get 'notifications/notify' => 'notifications#notify'

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  # default_scope -> { order(created_at: :desc)}
  default_scope -> { order(due_date: :desc)}
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tasks, dependent: :destroy

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: {minimum: 6}

  has_secure_password

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/concerns/webhookable.rb
module Webhookable
extend ActiveSupport::Concern
 
  def set_header
          response.headers["Content-Type"] = "text/xml"
  end
 
  def render_twiml(response)
          render text: response.text
  end
 
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
 
  skip_before_action :verify_authenticity_token
 
  def notify
    text_message = ""
    @user = User.find(session[:user_id])
    @tasks = @user.tasks
    @tasks.each do |task|
      text_message.concat(task.content)
      text_message.concat("\n")
    end

    client = Twilio::REST::Client.new Rails.application.secrets.twilio_account_sid, Rails.application.secrets.twilio_auth_token

    message = client.messages.create from: '(770) 249-4448', to: '(678) 491-7762', body: text_message
  
    redirect_to tasks_path 

    if message.status == "queued"
      flash[:success] = "Text has been sent!"
    end

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    # binding.pry
    if @user && @user.authenticate(params[:session][:password])
      log_in @user
      redirect_to tasks_path
      return
    else
      flash.now[:danger] = "Invalid email and/or password"
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    # binding.pry
    @user=User.find(session[:user_id])
    @tasks=Task.where("user_id=?", @user.id)
    render
  end

  def show
    @task=Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create

    @task = Task.new(task_params)
    @task.user_id = session[:user_id]
    if @task.save
      redirect_to tasks_path
    else
      render plain: "error"
    end
  end

  def edit
    @user = User.find(session[:user_id])
  end

  def update
   # @user = User.find(session[:id])
   # @task = Task.update_attributes(completed: params[:completed]
  end


  def destroy
    @user = User.find(session[:user_id])
    @task = @user.tasks.find(params[:id])

    @task.destroy
   
    respond_to do |format|
      format.js {render inline: "location.reload();" }
      format.html { redirect_to tasks_path }
      format.json { head :no_content }
   #  format.js   { render :layout => false }
    end
  end


  private

      def task_params
        params.require(:task).permit(:content, :completion, :due_date)
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      if @user.tasks.first.nil?
        redirect_to new_task_path
        # render "tasks/new"
        return
      else
        render :new
        return
      end
    else
      render :new
      #error message
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      ###
    else
      render :edit
      ##error message
    end

  end

  def destroy
    @user = User.find(params[:id])
    @user.delete
  end

  private

    def user_params
      params.require(:user).permit(:username,:email,:password,:password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    binding.pry
    @current_user ||= @user.find(id: session[:user_id])
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todotext</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%=pluralize(@user.errors.count, "error") %>
    </div>
    <ul>
      <% @user.errors.full_messages.each do |e| %>
        <li><%= e %> </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/destroy.js.erb
$('.delete_task').bind('ajax:success', function() {
   $(this).closest('tr').fadeOut();
});

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>

app/views/tasks/index.html.erb
<header>
<h1 class="headline_task">
  <%= @user.username %>'s Dashboard
</h1>
<div><%= button_to 'Log out', logout_path, method: :delete, class: "btn btn-warning btn-sm" %></div>
</header>

<table class="table table-striped">
<thead>
  <tr>
    <th>TASK</th>
    <th>DUE DATE</th>
    <th>COMPLETED?</th>
  </tr>
</thead>
<tbody>
   <% @tasks.each do |task| %>

    <tr class="task-wrapper">
      <td> <%= task.content %></td>
      <td> <%= task.due_date.strftime("%x") %></td>
   
      <td> <%= link_to 'Did it!', task, method: :delete, :remote => true, :class => 'delete_task' %> </td>
    </tr>
    <% end %>
</tbody>
</table>



<p><%=button_to 'Add New Task', new_task_path, method: :get, form_class: "new_task" %></p>

<p><%=button_to 'Text Tasks', '/notifications/notify', form_class: "text_task" %> </p>

app/views/tasks/index.js.erb
// $('.sent_text').click(function(){
//         if ($('.sent_text').text === "Text list to phone") {
//             $('.sent_text').text = "Text has been sent";
//         } else {
//             $('.sent_text').text = "Text list to phone";
//         }
//     });

// $('.SentText').click(function(){
//   var button = document.getElementsByClassName("SentText");
//         if (button.value === "Text list to phone") {
//             button.value = "Text has been sent";
//         } else {
//             button.value = "Text list to phone";
//         }
//     });

// $('.SentText').toggle(function(){
//     $(this).val('Text list to phone');
// }, function(){
//     $(this).val('Text has been sent');
// });


// $('.sent_text').click(function(){
//   if($('.sent_text').hasClass('.sent_text')){
//     $('.sent_text').text('Text list to phone');
//   } else {
//     $('.sent_text').text('Sent text');
//   }
// });
// binding.pry
// $('.sent_text').click(function(){
//   if($('.sent_text').text('Text list to phone'){
//     $('.sent_text').text('Sent text');
//   } else {
//     $('.sent_text').text('Text list to phone');
//   }
// });

// $('.sent_text').click(function(){
//   var sText = document.getElementById('.sent_text')
//   if(sText.text === 'Text list to phone'){
//     sText.text = 'Sent text';
//   } else {
//     sText.text = 'Text list to phone';
//   }

// })

app/views/tasks/new.html.erb
<h1 class = "newtask_headline"> Tasks </h1>

<%= form_for @task do |t| %>
  <%= t.label :content %>:
  <%= t.text_field :content %><br />

  <%= t.label :due_date %>
  <%= t.date_field :due_date %><br />

  <%= t.submit %>
<% end %>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control'  %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control'  %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control'  %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1> Users/Show - Welcome <%=@user.username %> </h1>